### ISSUE TITLE
Crafting Frames | Non-Solid Blocks

### ISSUE THREAD

**Issue by WispHalfPast** [InventivetalentDev/CraftingFrames#1]
## What steps will reproduce the problem?
1. Place a crafting frame on a block (This error has only occurred on an enchant table and doors)
2. Break the crafting frame
3. There's a small chance that the crafting table will stay and either an item frame or crafting frame will drop
## What were you expecting to happen? What happened instead?

I expected the crafting frame to be broken and remove the crafting table at all times
## What version of the plugin are you using? _Type /version &lt;Plugin Name&gt;_

1.0.2 CraftingFrames
## Did your client crash? _Upload errors in .minecraft/logs/latest.log as well_

No
## Additional information?  _(Are you using Bungeecord? Did it work in previous versions? etc.)_

Not using Bungeecord, and never tried it before updating to Spigot 1.10

**Comment by InventivetalentDev** [comment]
Please update to the latest plugin version (1.0.4). I tried it on multiple non-solid blocks and it seems to work fine.

**Comment by WispHalfPast** [comment]
There's no section on the plugin Bookshelves, but could you add support so people can't open them in other people's claims through GriefPrevention? And maybe add WorldGuard support and make them act as chests?

**Comment by InventivetalentDev** [comment]
That's not related to CraftingFrames. Post it in the Bookshelves thread, please.

**Comment by WispHalfPast** [comment]
I would, but sadly there is no Bookshelves thread as noted in my last comment.

**Comment by InventivetalentDev** [comment]
https://www.spigotmc.org/threads/bookshelves.96781/ ? I'm aware that there's not GitHub issue tracker for it, but there is a thread.
